option(SANITIZE "Option referring to sanitizers (cppcheck, iwyu, additional warnings)" OFF)
option(BINARY_DEPS "Option referring to dependency installation (OFF - compile from source, ON - download binaries)" ON)
option(GENERATE_DEPENDENCY_GRAPH "Option referring to dependency graph generation in png format" OFF)
option(GENERATE_INCLUDE_GRAPH "Option referring to include graph generation in png format" OFF)
option(FORMAT_SOURCE "Option referring to formatting before compiling" OFF)
