name: Ubuntu CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-24.04]
        build_type: [Release, Debug]
        cpp_compiler: [g++, clang++]

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Setup ccache
      uses: Chocobo1/setup-ccache-action@v1

    - name: Set up cache
      id: cache-cpm
      uses: actions/cache@v4
      with:
        path: ~/cpm-cache
        key: ${{ runner.os }}-cpm-${{ hashFiles('**/') }}
        restore-keys: |
          ${{ runner.os }}-cpm-a

    # Download VulkanAPI
    - name: Setup Vulkan
      uses: humbletim/setup-vulkan-sdk@523828e49cd4afabce369c39c7ee6543a2b7a735
      with:
        vulkan-query-version: latest
        vulkan-components: Vulkan-Headers Vulkan-Loader SPIRV-Headers SPIRV-Cross SPIRV-Tools SPIRV-Reflect Glslang
        vulkan-use-cache: true

    # Download GLFW dependencies
    - name: Setup GLFW deps
      run: |
        sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
        sudo apt-get update
        sudo apt-get build-dep glfw3

    - name: Setup Mold
      run: |
        sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
        sudo apt-get update
        sudo apt-get install mold

    - name: Configure CMake (GCC)
      if: ${{ matrix.cpp_compiler == 'g++' }}
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCPM_SOURCE_CACHE=~/cpm-cache
        -DCMAKE_CXX_COMPILER=g++
        -DCMAKE_C_COMPILER=gcc
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Configure CMake (Clang)
      if: ${{ matrix.cpp_compiler == 'clang++' }}
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCPM_SOURCE_CACHE=~/cpm-cache
        -DCMAKE_CXX_COMPILER=clang++
        -DCMAKE_C_COMPILER=clang
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}


    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}
